export {default as Categories} from './Categories'
export {default as Watch} from './Watch'
export {default as Search} from './Search'
export {default as Register} from './Register'
export {default as Navbar} from './Navbar'