export {default as Categories} from './Categories'
export {default as Watch} from './Watch'
export {default as Search} from './Search'
export {default as Studio} from './Studio'
export {default as Register} from './Register'